name = "streetwarecity-api"
domainChoice = "pxxl.pro"
framework = "express"
language = "javascript"
packageManager = "npm"
port = 4000
installCommand = "npm ci --include=dev"
buildCommand = "npm run build && echo BUILD_PWD=$(pwd) && ls -la dist || echo DIST_MISSING"
startCommand = "echo START_PWD=$(pwd) && ls -la && ls -la dist || echo DIST_MISSING_AT_START; npm run start:prod"
outputDirectory = "dist"
projectId = "proj_ytjspqpaj7fp6ghcz9pi"
deploymentId = "dep_nirzx3c6imcl9u9zm1qmi"
projectUrl = "https://streetwarecity-api.pxxl.pro"
deploymentUrl = "https://pxxl.app/dashboard/projects/proj_ytjspqpaj7fp6ghcz9pi/deployments/dep_nirzx3c6imcl9u9zm1qmi"
lastDeployedAt = "2026-07-28T19:42:58.552Z"

[env]
NODE_ENV = "production"
